### ISSUE TITLE
Make a new release of the library

### ISSUE THREAD

**Issue by umbynos** [openmv/openmv-arduino-rpc#10]
The library still fails to install with the arduino-cli and with IDE2.x
```
$ arduino-cli lib install "OpenMV Arduino RPC"
Error installing OpenMV Arduino RPC: No valid dependencies solution found: dependency 'SoftwareSerial' is not available
```
The problem seems to have been fixed in https://github.com/openmv/openmv-arduino-rpc/pull/9 and already merged, but not yet part of a release: https://github.com/openmv/openmv-arduino-rpc/blob/v1.0.7/library.properties#L10

**Comment by kwagyeman** [comment]
Done: https://github.com/openmv/openmv-arduino-rpc/releases/tag/v1.0.8
